version: '3.7'

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.local
    image: los_app:dev
    container_name: los_app
    restart: "on-failure"

    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      - .:/app/las
      - static_volume:/app/las/static

    # command directive passes the parameters to the service and they will be executed by the service.
    # In this example, these are django commands which will be executed in the container where django lives.
    # FIXME: User gunicorn for deployed server
    command: sh -c "python manage.py collectstatic --noinput &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:11-alpine 
    container_name: postgres
    restart: "on-failure"

    ports:
      - "5431:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/

    # access credentials from the .env file
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}


volumes:
  postgres_data:
  static_volume:
