version: '3.7'

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.local
    image: las_app:dev
    container_name: las_app
    restart: "on-failure"

    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      - .:/app/las
      - static_volume:/app/las/static

    # command directive passes the parameters to the service and they will be executed by the service.
    # In this example, these are django commands which will be executed in the container where django lives.
    # FIXME: User gunicorn for deployed server
    command: sh -c "python manage.py collectstatic --noinput &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.0.32
    container_name: mysql
    restart: "on-failure"

    ports:
    - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql/

    # NOTE: use of "mysql_native_password" is not recommended:
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --authentication_policy=mysql_native_password

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}


volumes:
  mysql_data:
  static_volume:
