# Generated by Django 4.1.5 on 2023-04-24 00:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hexcolor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
