# Generated by Django 4.1.5 on 2023-05-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_course_hexcolor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='program',
        ),
    ]
