# Generated by Django 4.1.5 on 2023-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_course_program_rename_course_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('shs', 'Senior High School'), ('und', 'Undergraduate'), ('grd', 'Graduate')], default='und', max_length=3),
        ),
    ]
