# Generated by Django 4.1.5 on 2023-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('shs', 'Senior High School'), ('und', 'Undergraduate'), ('grd', 'Graduate')], default='und', max_length=3),
        ),
    ]
